<?PHP
	// Global Application Configuration
	require_once ('../repository_inc/classes/inc.global.php');
	showErrors();
	set_time_limit(0);
	$songs = array(
		"As You Said.mp3",
		"_As You Said",
		"3-Piano-As You Said",
		"As You Said 30",
		"As You Said 60",
		"Autumn_Souvenir_Le_Dantec_KT",
		"Awakening",
		"_Awakening",
		"7-Universal-Awakening",
		"Awakening 30",
		"Awakening 60",
		"Breezy and Mild",
		"_Breezy and Mild",
		"7-Universal-Breezy and Mild",
		"Breezy and Mild 30",
		"Breezy and Mild 60",
		"Brighten Up",
		"_Brighten Up",
		"7-Universal-Brighten Up",
		"Brighten Up 30",
		"Brighten Up 60",
		"Calm River 60",
		"7-Universal-Calm River",
		"_Calm River 60",
		"Can Do",
		"_Can Do",
		"7-Universal-Can Do",
		"Can Do 30",
		"Can Do 60",
		"Carry On",
		"_Carry On",
		"7-Universal-Carry On",
		"Carry On 30",
		"Carry On 60",
		"Cat Briar Road",
		"_Cat Briar Road",
		"5-Western-Cat Briar Road",
		"Cat Briar Road 30",
		"Cat Briar Road 60",
		"crystal liquid",
		"1-Jazzy-Crystal Liquid",
		"Dawn Mist",
		"_Dawn Mist",
		"7-Universal-Dawn Mist",
		"Dawn Mist 30",
		"Dawn Mist 60",
		"Far From Home",
		"_Far From Home",
		"2-Peaceful-Far From Home",
		"Far From Home 30",
		"Far From Home 60",
		"Good Night Kiss",
		"_Good Night Kiss",
		"7-Universal-Good Night Kiss",
		"Good Night Kiss 30",
		"Good Night Kiss 60",
		"ile de groove",
		"1-Jazzy-Ile de Groove",
		"Journeys End",
		"_Journeys End",
		"2-Peaceful-Journeys End",
		"Journeys End 30",
		"Journeys End 60",
		"Just Enough",
		"_Just Enough",
		"2-Peaceful-Just Enough",
		"Just Enough 30",
		"Just Enough 60",
		"Natural Beauty",
		"_Natural Beauty",
		"4-Dramatic-Natural Beauty",
		"Natural Beauty 30",
		"Natural Beauty 60",
		"October Sunset",
		"_October Sunset",
		"7-Universal-October Sunset",
		"October Sunset 30",
		"October Sunset 60",
		"On The Water 1",
		"_On The Water",
		"4-Dramatic-On The Water",
		"On The Water 30",
		"On The Water 60",
		"Quiet Storm",
		"_Quiet Storm",
		"3-Piano-Quiet Storm",
		"Quiet Storm 30",
		"Quiet Storm 60",
		"Show Me The Way",
		"_Show Me The Way",
		"3-Piano-Show Me The Way",
		"Show Me The Way 30",
		"Show Me The Way 60",
		"Thats What I Like About You",
		"_Thats What I Like About You",
		"3-Piano-Thats What I Like About You",
		"Thats What I Like About You 30",
		"Thats What I Like About You 60"
	);
	foreach($songs as $index => $song){
		$slideshowsWithSongAndYT = $db->run("SELECT pt.photoTourID as slideShowID FROM photo_tours pt WHERE pt.musicURL LIKE '%".$song."%' AND (SELECT COUNT(vidProgressID) FROM video_progress WHERE type='slideshow' AND step>0 AND updated<'2014-08-25 00:00:00' AND typeID=pt.photoTourID)>0");
		foreach($slideshowsWithSongAndYT as $rows => $columns){
			$db->run("UPDATE video_progress SET step='0' WHERE type='slideshow' AND typeID='".$columns['slideShowID']."'");
		}
	}
?>