<?php
/**********************************************************************************************
Document: concierge/microsite.php
Creator: Jeff Sylvester & Jacob Edmond Kerr
Date: 09-09-16
Purpose: Spotlight's Concierge Microsite setup page 
**********************************************************************************************/
//=======================================================================
// Includes
//=======================================================================

	// HEADER TEMPLATE
	// Get rand number to force fresh download of CSS and JS to avoid cache issues
	$homeRandNum = rand(999999,999999999);
	$title = 'Spotlight | Concierge Microsite Setup';
	$header = '
<link href="https://fonts.googleapis.com/css?family=Nunito:300" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="css/microsite.css"/>
';
	require_once('../repository_inc/template-header.php');
	
//=======================================================================
// Document
//=======================================================================
	
?>
	<div class="concierge-set-up">
		<div id="setup"><strong>Step 3:</strong> Setup your Microsites</div>
		<div id="concierge-line"><img src="images/concierge-line.png" alt="line" /></div>
		<div id="concierge-logo"><img src="images/concierge-logo.png" alt="logo" /></div>
		<div id="topbar-logo">
			<div id="microsite-logo"><img src="images/microsite.png" alt="microsite" width="150px"/></div>
		</div>
		<div id="topbar-text">
			<div id="microsite-manager">Microsite Manager</div>
			<div id="microsite-text">This page allows you to choose which template you would like for your microsites. If you already have an existing microsite, you can enter that into the URL, your microsite will forward to that address instead of showing the microsite generated by Spotlight Home Tours.</div>
		</div>
		<div id="concierge-line2"> <img src="images/concierge-line.png" alt="line" /> </div>
		<div id="microsite-frame">
			<iframe height="600" width="900" src="http://www.spotlighthometours.com/users/new/microsites-include.php?level=user"></iframe>
		</div>
		<div id="previous-step"><a href="tour-window.php"><img src="images/previous-step.png" alt="previous-step" width="150px"/></a></div>
		<div id="save-exit"><a href="set-up.php"><img src="images/save-exit.png" alt="save-exit" width="150px"/></a></div>
		<div id="next-step"><a href="social-hub.php"><img src="images/next-step.png" alt="next-step" width="150px"/></a></div>
		<br />
	</div>
<?PHP
	// FOOTER TEMPLATE
	require_once('../repository_inc/template-footer.php');
?>