valign="top" width="NaN%"><p>DECLARE</p>
</td>
<td valign="top" width="NaN%"><p>DEFAULT</p>
</td>
</tr>
<tr><td valign="top" width="NaN%"><p>DEFERRABLE</p>
</td>
<td valign="top" width="NaN%"><p>DEFERRED</p>
</td>
<td valign="top" width="NaN%"><p>DELETE</p>
</td>
<td valign="top" width="NaN%"><p>DESC</p>
</td>
<td valign="top" width="NaN%"><p>DESCRIBE</p>
</td>
</tr>
<tr><td valign="top" width="NaN%"><p>DESCRIPTOR</p>
</td>
<td valign="top" width="NaN%"><p>DIAGNOSTICS</p>
</td>
<td valign="top" width="NaN%"><p>DISCONNECT</p>
</td>
<td valign="top" width="NaN%"><p>DISTINCT</p>
</td>
<td valign="top" width="NaN%"><p>DOMAIN</p>
</td>
</tr>
<tr><td valign="top" width="NaN%"><p>DOUBLE</p>
</td>
<td valign="top" width="NaN%"><p>DROP</p>
</td>
<td valign="top" width="NaN%"><p>ELSE</p>
</td>
<td valign="top" width="NaN%"><p>END</p>
</td>
<td valign="top" width="NaN%"><p>END-EXEC</p>
</td>
</tr>
<tr><td valign="top" width="NaN%"><p>ESCAPE</p>
</td>
<td valign="top" width="NaN%"><p>EXCEPT</p>
</td>
<td valign="top" width="NaN%"><p>EXCEPTION</p>
</td>
<td valign="top" width="NaN%"><p>EXEC</p>
</td>
<td valign="top" width="NaN%"><p>EXECUTE</p>
</td>
</tr>
<tr><td valign="top" width="NaN%"><p>EXISTS</p>
</td>
<td valign="top" width="NaN%"><p>EXTERNAL</p>
</td>
<td valign="top" width="NaN%"><p>EXTRACT</p>
</td>
<td valign="top" width="NaN%"><p>FALSE</p>
</td>
<td valign="top" width="NaN%"><p>FETCH</p>
</td>
</tr>
<tr><td valign="top" width="NaN%"><p>FIRST</p>
</td>
<td valign="top" width="NaN%"><p>FLOAT</p>
</td>
<td valign="top" width="NaN%"><p>FOR</p>
</td>
<td valign="top" width="NaN%"><p>FOREIGN</p>
</td>
<td valign="top" width="NaN%"><p>FOUND</p>
</td>
</tr>
<tr><td valign="top" width="NaN%"><p>FROM</p>
</td>
<td valign="top" width="NaN%"><p>FULL</p>
</td>
<td valign="top" width="NaN%"><p>GET</p>
</td>
<td valign="top" width="NaN%"><p>GLOBAL</p>
</td>
<td valign="top" width="NaN%"><p>GO</p>
</td>
</tr>
<tr><td valign="top" width="NaN%"><p>GOTO</p>
</td>
<td valign="top" width="NaN%"><p>GRANT</p>
</td>
<td valign="top" width="NaN%"><p>GROUP</p>
</td>
<td valign="top" width="NaN%"><p>HAVING</p>
</td>
<td valign="top" width="NaN%"><p>HOUR</p>
</td>
</tr>
<tr><td valign="top" width="NaN%"><p>IDENTITY</p>
</td>
<td valign="top" width="NaN%"><p>IMMEDIATE</p>
</td>
<td valign="top" width="NaN%">&#160;</td>
<td valign="top" width="NaN%"><p>IN</p>
</td>
<td valign="top" width="NaN%">&#160;</td>
</tr>
<tr><td valign="top" width="NaN%">&#160;</td>
<td valign="top" width="NaN%">&#160;</td>
<td valign="top" width="NaN%">&#160;</td>
<td valign="top" width="NaN%"><p>INDICATOR</p>
</td>
<td valign="top" width="NaN%"><p>INITIALLY</p>
</td>
</tr>
<tr><td valign="top" width="NaN%"><p>INNER</p>
</td>
<td valign="top" width="NaN%"><p>INPUT</p>
</td>
<td valign="top" width="NaN%"><p>INSENSITIVE</p>
</td>
<td valign="top" width="NaN%"><p>INSERT</p>
</td>
<td valign="top" width="NaN%"><p>INT</p>
</td>
</tr>
<tr><td valign="top" width="NaN%">&#160;</td>
<td valign="top" width="NaN%">&#160;</td>
<td valign="top" width="NaN%">&#160;</td>
<td valign="top" width="NaN%">&#160;</td>
<td valign="top" width="NaN%">&#160;</td>
</tr>
<tr><td valign="top" width="NaN%"><p>INTEGER</p>
</td>
<td v